### ISSUE TITLE
Error after new plugin update

### ISSUE THREAD

**Issue by MasamuneDate99** [rauenzi/BDPluginLibrary#147]
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.ao (https://discord.com/assets/6f597d3d51d44c761a42.js:6207:204)
    at t.useRef (https://discord.com/assets/6f597d3d51d44c761a42.js:6355:990)
    at _ (https://discord.com/assets/6f597d3d51d44c761a42.js:4492:127)
    at t.useStateFromStoresObject (https://discord.com/assets/6f597d3d51d44c761a42.js:4490:734)
    at Object.j [as openModal] (https://discord.com/assets/b8aa8cb9b8691baaaacf.js:431:621)
    at Function.showModal (betterdiscord://plugins/0PluginLibrary.plugin.js:4749:81)
    at Function.showChangelogModal (betterdiscord://plugins/0PluginLibrary.plugin.js:4811:23)
    at PluginLibrary.showChangelog (betterdiscord://plugins/0PluginLibrary.plugin.js:3938:64)
    at PluginLibrary.load (betterdiscord://plugins/0PluginLibrary.plugin.js:3898:22)
    at PluginLibrary.load (betterdiscord://plugins/0PluginLibrary.plugin.js:3384:19)
    at Object.initializeAddon (<anonymous>:4:42300)
    at Object.loadAddon (<anonymous>:4:9075)
    at Object.loadAddon (<anonymous>:4:40847)
    at FSWatcher.<anonymous> (<anonymous>:4:7059)

![image](https://user-images.githubusercontent.com/24244933/192470107-c54fd4b4-5924-48bf-8c1c-bc2debcb27a5.png)

**Comment by SmolAlli** [comment]
duplicate of #143

**Comment by Gal1le0Oo** [comment]
SAMEEE

**Comment by Gal1le0Oo** [comment]
what do you mean by 'updating'

**Comment by trungnt2910** [comment]
Seems like I'm on `ZeresPluginLibrary` version 2.0.6 (the one that contains the fix mentioned in that issue) but several of my installed plugins failed to compile, including the one I built myself.

![image](https://user-images.githubusercontent.com/57174311/192475994-b8392159-b790-4e03-b6e3-f527a71c2bfc.png)

I'm quite sure this library is related because the plugins in the list above all uses ZeresPluginLibrary, and other plugins installed on my BetterDiscord works fine.

**Comment by LoicTomatot** [comment]
Is there a way to recover the file before this broken update ?

**Comment by NotAllowIce1102** [comment]
same issue

**Comment by Andryshik345** [comment]
for those, who wants temporarily revert it back, replace the contains of your file (or save the page as a file) from here: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/b3f40780361f7de2f2fec8d25e86866bdb89dcab/release/0PluginLibrary.plugin.js

**Comment by SW213** [comment]
same issue

**Comment by AviationRam** [comment]
I've also tried to revert the update back to V2.0.5 with no luck.

**Comment by lukaseds** [comment]
yes i have the problem also half of my plugins don't work anymore

**Comment by Technetium1** [comment]
Everything is broken thanks to a major update from Discord. There is no ETA on any fixes for any libraries, or BBD itself.

**Comment by TheUndeadCpt** [comment]
Was getting this error till I reinstalling discord/bd, have you tried that? If not doing what Andry said worked for me before I reinstalled.

**Comment by angrybirdice** [comment]
didnt work
