### ISSUE TITLE
Unable to compile (2.0.9)

### ISSUE THREAD

**Issue by rastafaa** [rauenzi/BDPluginLibrary#160]
I've been getting this error since 2.0.9 update each time it tries to load.

error log:

```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object../src/ui/popouts.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4516:39)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at Object../src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6114:66)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at Object../src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1707:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at Object../src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3579:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at Object../src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3807:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at Object../src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:651:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at Object../src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1562:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6153:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6200:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6307:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6310:12)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)
```

**Comment by rastafaa** [comment]
Nevermind, updating discord and betterdiscord to latest versions fixed this issue
