### ISSUE TITLE
"Plugin constructor() could not be fired"

### ISSUE THREAD

**Issue by ScripterRickster** [rauenzi/BDPluginLibrary#189]
This issue quite literally occurred right around 6:40 PM EST when the plugin suddenly fails to load at startup. I've uninstalled and re-installed this plugin however it continues to give the same error. Attached below is the error:

TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://discord.com/assets/6b9fd512448164a3644d.js:1781:54)
    at gu (https://discord.com/assets/6b9fd512448164a3644d.js:1835:146)
    at Ic (https://discord.com/assets/6b9fd512448164a3644d.js:1828:89)
    at mc (https://discord.com/assets/6b9fd512448164a3644d.js:1828:17)
    at hc (https://discord.com/assets/6b9fd512448164a3644d.js:1827:867)
    at uc (https://discord.com/assets/6b9fd512448164a3644d.js:1824:983)
    at Fi (https://discord.com/assets/6b9fd512448164a3644d.js:1764:577)
    at lc (https://discord.com/assets/6b9fd512448164a3644d.js:1825:498)
    at https://discord.com/assets/6b9fd512448164a3644d.js:1844:522
    at el (https://discord.com/assets/6b9fd512448164a3644d.js:1844:561)
    at t.render (https://discord.com/assets/6b9fd512448164a3644d.js:1848:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at A.loadAllAddons (betterdiscord/renderer.js:4:10099)
    at A.initialize (betterdiscord/renderer.js:4:4521)
    at A.initialize (betterdiscord/renderer.js:4:31995)
    at Object.startup (betterdiscord/renderer.js:4:357022)

**Comment by rauenzi** [comment]
Already fixed, and duplicate issue x2

**Comment by theapathyimp** [comment]
I am getting this still at this exact moment. Manually downloaded and replaced the plugin as the first step.

![image](https://user-images.githubusercontent.com/8020193/232166996-57a76b82-7c6b-4073-8e86-f926b7f5f887.png)
