### ISSUE TITLE
PTB: TypeError: Cannot read properties of undefined (reading 'Provider')

### ISSUE THREAD

**Issue by Benny-Boo** [rauenzi/BDPluginLibrary#192]
`TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1779:54)
    at gu (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1833:146)
    at Ic (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1826:89)
    at mc (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1826:17)
    at hc (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1825:867)
    at uc (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1822:983)
    at Fi (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1762:577)
    at lc (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1823:498)
    at https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1842:522
    at el (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1842:561)
    at t.render (https://ptb.discord.com/assets/3696d2cc92d52d914b0f.js:1846:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at A.reloadAddon (betterdiscord/renderer.js:4:8515)
    at AsyncFunction.<anonymous> `(betterdiscord/renderer.js:4:5651)`
    
    I saw a similar issue that was closed, but I am on 2.0.15, and this issue just popped up last night for me. I have already tried 
    reinstalling the plugin, to no avail.

**Comment by wilecoyote** [comment]
Same Problem here on Discord Ptb 200062 (ddb6205) and Canary 200062 (ddb6205)

![image](https://github.com/rauenzi/BDPluginLibrary/assets/1034673/b1eb01c2-ac97-443f-a7f0-d87a7648cc57)
![image](https://github.com/rauenzi/BDPluginLibrary/assets/1034673/37e693d3-3541-44ee-949f-9edfbe53bd97)

**Comment by NotDreppy** [comment]
It's not only PTB that is affected. Same issue with Canary.

Version: Canary 200139 (a21c6af)
Host: v-1.0.63 (32746)
Operating System: Windows 11 Pro x64 (10.0.22621.1702)

![image](https://github.com/rauenzi/BDPluginLibrary/assets/93709292/ef508959-adf9-412e-90a2-67c996f88082)

**Comment by Salty-Coder** [comment]
I wonder if we're going to see a fix anytime soon....

**Comment by Benny-Boo** [comment]
closing it cause it's the same as #193 but this doesn't have different info
