### ISSUE TITLE
Plugin constructor() could not be fired.

### ISSUE THREAD

**Issue by Salty-Coder** [rauenzi/BDPluginLibrary#193]
For the past day or 2, I have been getting this error:
![image](https://github.com/rauenzi/BDPluginLibrary/assets/59771980/5b4e8042-058e-41f7-8419-915f8ef2cbbd)

I am using the latest version of ZeresPluginLibrary on Discord Canary.

How can I fix this issue?

The full error is here:
```TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1779:54)
    at gu (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1833:146)
    at Ic (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1826:89)
    at mc (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1826:17)
    at hc (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1825:867)
    at uc (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1822:983)
    at Fi (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1762:577)
    at lc (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1823:498)
    at https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1842:522
    at el (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1842:561)
    at t.render (https://canary.discord.com/assets/1a9a618b93cd3472669e.js:1846:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5617)```

**Comment by ParaliyzedEvo** [comment]
https://canary.discord.com/channels/86004744966914048/1110266188728119379

**Comment by Salty-Coder** [comment]
> https://canary.discord.com/channels/86004744966914048/1110266188728119379

I can't access that 🫤

**Comment by Benny-Boo** [comment]
same as my (and other's) issue in #192, as well as I think #187, which was allegedly solved in 2.0.15, but it's definitely still here

**Comment by SourCandy80** [comment]
New issue. Please fix.

**Comment by SourCandy80** [comment]
> https://canary.discord.com/channels/86004744966914048/1110266188728119379

Please tell us what this is.

**Comment by zulc22** [comment]
latest version, still being reproduced, on discord PTB.
```
TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1779:54)
    at gu (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1833:146)
    at Ic (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1826:89)
    at mc (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1826:17)
    at hc (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1825:867)
    at uc (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1822:983)
    at Fi (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1762:577)
    at lc (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1823:498)
    at https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1842:522
    at el (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1842:561)
    at t.render (https://ptb.discord.com/assets/1b2fbb480f1471917573.js:1846:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at A.reloadAddon (betterdiscord/renderer.js:4:8515)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5651)
```

**Comment by Benny-Boo** [comment]
idk about that, I've got at least one plugin that worked fine before the error started happening. Idk if there's more cause idk how/if i can find out what uses the library, but they definitely aren't working normal.

**Comment by Salty-Coder** [comment]
> idk about that, I've got at least one plugin that worked fine before the error started happening. Idk if there's more cause idk how/if i can find out what uses the library, but they definitely aren't working normal.

I'm not too sure if it's a different issue or caused by Zeres but MessageLoggerV2 has been failing to start ever since I started getting this Zeres error...

**Comment by pearwb1235** [comment]
(I am not good at English)

在插件修復好之前，我嘗試自己做了簡單處理
(Before plugin fixed, I try to fix it with self.)
https://github.com/rauenzi/BDPluginLibrary/blob/683d6abc70f149a39e2f0433ffb65e55ca47c4e3/release/0PluginLibrary.plugin.js#L4521
替換成 (Replace to)
```javascript
const ThemeContext = modules__WEBPACK_IMPORTED_MODULE_0__.WebpackModules.getAllModules()[709105].exports.wM;
```

現在能正常運行
(Now it working to me.)
直到插件作者修復之前
我只能使用這個方案
(Before plugin fixed, I can only use this solution.)

注意：這個方式可能會在Discord更新後失效
(Warning: This fix method may become invalid after Discord update.)

**Comment by ItMeSarah** [comment]
> I'm not too sure if it's a different issue or caused by Zeres but MessageLoggerV2 has been failing to start ever since I started getting this Zeres error...

Good. We don't support message loggers.

**Comment by Benny-Boo** [comment]
> idk about that, I've got at least one plugin that worked fine before the error started happening. Idk if there's more cause idk how/if i can find out what uses the library, but they definitely aren't working normal.

for some reason, it just kinda started worked yesterday, the library still tells me it fails to launch every single time i start discord, so i guess if it's not breaking anything it's just annoying ?

**Comment by Salty-Coder** [comment]
> for some reason, it just kinda started worked yesterday, the library still tells me it fails to launch every single time i start discord, so i guess if it's not breaking anything it's just annoying ?

Yeah. It seems that no plugins are actually affected by this bug...

**Comment by SourCandy80** [comment]
> No greater evil can exist than the saving of messages that you have rightful access to... that's what killed AOL Instant Messenger.

Thank you so much to @Lucatir and @ImportTaste for having common sense. This whole situation with people hating on a plugin that lets you save messages is ridiculous.

**Comment by Benny-Boo** [comment]
> > Good. We don't support message loggers.
> 
> I love the display of insecurity whenever someone says "we", referring to a vague, undefined group (as it makes the often fringe stance seem more common at the same time), instead of saying "I" in an attempt to make it sound more authoritative, essentially using peer pressure to make "wrongthinkers/doers" fall in line.

To be fair on them, it says on their profile that they're a moderator for BetterDiscord, so it's pretty clear the "we" is the BD team.

However, there's not really much more discord says against message loggers than just the same line that says Discord is against BD. 
Personally, I don't really find that much issue with it, if someone sends a message, they should be prepared for it to get preserved in any of the various ways discord actually does allow, such as Dyno's logs or screenshots. Discord cites privacy concerns, but I don't see how it's any different. The message logger plugin is just a simpler way to do the same thing.

**Comment by ScripterRickster** [comment]
Can confirm this issue is now on the stable version of Discord.

**Comment by SourCandy80** [comment]
> Can confirm this issue is now on the stable version of Discord.

Message logger somehow still works. Weird.

**Comment by SourCandy80** [comment]
> > > No greater evil can exist than the saving of messages that you have rightful access to... that's what killed AOL Instant Messenger.
> > 
> > 
> > Thank you so much to @Lucatir and @ImportTaste for having common sense. This whole situation with people hating on a plugin that lets you save messages is ridiculous.
> 
> What? No, I'm admonishing you. You're like one of those demons that record television shows with "VCR"s.

I seriously cant tell if you are joking or not lmao

**Comment by MagmaBro123** [comment]
Still not fixed.

**Comment by Rxcap** [comment]
Need it fixed twin I was the Only one

**Comment by Salty-Coder** [comment]
#To all the new people having this issue on stable build:

This bug is **unlikely** to cause any issues with plugins. All plugins **should** function normally.
Hopefully this gets fixed soon though as it's a bit annoying.

**Comment by Alluseri** [comment]
*Just* started happening to me after Discord crashed once. Weird.

**Comment by Salty-Coder** [comment]
> *Just* started happening to me after Discord crashed once. Weird.

That will be because Discord checks for updates when it's launched.
It would have happened sooner or later anyway.

**Comment by Salty-Coder** [comment]
It's kind of funny to see suddenly all these hundreds of people start appearing and creating new issues the moment Discord pushes to stable

**Comment by Salty-Coder** [comment]
> > ## To all the new people having this issue on stable build:
> > This bug is **unlikely** to cause any issues with plugins. All plugins _should_ function normally. Hopefully this gets fixed soon though as it's a bit annoying.
> 
> Mostly true. Only MessageLoggerV2 has stopped working for me, as has been stated by others here.

I thought that too, I contacted the developer of the improved version and he gave me [some fixed code](https://github.com/Salty-Coder/MessageLoggerV2-fixed). Turns out it was unrelated to Zeres.

**Comment by Wrobel1111** [comment]
Fixed code from the comment above makes the Message Logger work, so most of the folks here will be satisfied, however this isn't fix for the plugin library itself

**Comment by Salty-Coder** [comment]
> Fixed code from the comment above makes the Message Logger work, so most of the folks here will be satisfied, however this isn't fix for the plugin library itself

Yes. As I have previously said, the bug with Zeres will hopefully get fixed soon but doesn't affect the usage of any other plugins.
The code I provided above is just for an issue with MessageLoggerV2 that was unrelated to Zeres but caused by the same Discord update.

**Comment by rauenzi** [comment]
The root issue has been fixed in the latest version. Any issues you have with unofficial plugins are not of a concern to me.

**Comment by Salty-Coder** [comment]
> The root issue has been fixed in the latest version. Any issues you have with unofficial plugins are not of a concern to me.

Are you planning to build the plugin or do we need to do that ourselves?

**Comment by rauenzi** [comment]
It was built as part of the commit as usual https://github.com/rauenzi/BDPluginLibrary/commit/f2dcca957161ae77dc763069f7b58212e422b591

**Comment by Wrobel1111** [comment]
But it's the other way around; Library doesn't work, thus Logger doesn't too, but provided fork of Logger makes it work independently
The code provided above in no way touches the library, which is the subject of this issue
