### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by ehte89** [rauenzi/BDPluginLibrary#201]
TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1779:54)
    at gu (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1833:146)
    at Ic (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1826:89)
    at mc (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1826:17)
    at hc (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1825:867)
    at uc (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1822:983)
    at Fi (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1762:577)
    at lc (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1823:498)
    at https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1842:522
    at el (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1842:561)
    at t.render (https://discord.com/assets/b2f5c23f3dcfbd8e7f9e.js:1846:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at A.loadAllAddons (betterdiscord/renderer.js:4:10099)
    at A.initialize (betterdiscord/renderer.js:4:4521)
    at A.initialize (betterdiscord/renderer.js:4:31995)
    at Object.startup (betterdiscord/renderer.js:4:357022)

**Comment by Salty-Coder** [comment]
Not a "new" error, duplicate of #193 and the hundreds of other duplicates.
