### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by BebroNUXXX** [rauenzi/BDPluginLibrary#208]
After latest Discord update this thing happend. Also it didnt work at Discord PTB for one week

**Comment by JonathanSwalens** [comment]
+1

**Comment by rauenzi** [comment]
Duplicate of #207

**Comment by B-Nerd** [comment]
for the creator here is the error log 
B-Nerd
endeavouros_kde
Online



Friends
Online
All
Pending
Blocked
Add Friend

ONLINE — 5

DaBanana64
Pizza Tower Halloween Update is PEAK!

DarkSide1305

The Slime Whisperer

KevinFreez
Do Not Disturb

Scorpiove
Idle

Steph the Blackcat
Playing FINAL FANTASY XIV
Active Now
It's quiet for now...
When a friend starts an activity—like playing a game or hanging out on voice—we’ll show it here!
ADDON ERRORS
Plugins
ZeresPluginLibrary
Plugin constructor() could not be fired.
TypeError: Cannot read properties of undefined (reading 'id')
    at https://discord.com/assets/c59ab0d49e4f72c7144b.js:1:1694838
    at l (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:919639)
    at U (https://discord.com/assets/c59ab0d49e4f72c7144b.js:1:1694778)
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:19)
    at iT (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:717663)
    at l (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:772873)
    at sj (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:755889)
    at https://discord.com/assets/e8fd2221603a9472ac4a.js:1:755755
    at sR (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:755763)
    at sO (https://discord.com/assets/e8fd2221603a9472ac4a.js:1:752848)
