### ISSUE TITLE
DoubleClickVoiceChannels Bug Looks Rooted your plugin

### ISSUE THREAD

**Issue by Rootkit-** [rauenzi/BDPluginLibrary#217]
![image](https://github.com/rauenzi/BDPluginLibrary/assets/5389279/69896335-8d0b-4c5e-bab5-aa4b0aeb6f6f)
Makes it not work

`Error: Menu API only allows Items and groups of Items as children. Received function _(e){return null} (object) instead
    at 72243.f03b84cab4a1c646abd0.js:1:113048
    at Array.reduce (<anonymous>)
    at e (72243.f03b84cab4a1c646abd0.js:1:111774)
    at T (72243.f03b84cab4a1c646abd0.js:1:113257)
    at eval (0BDFDB.plugin.js:2969:21)
    at ob (72054.ccb12939fa7033320d60.js:1:799947)
    at u (72054.ccb12939fa7033320d60.js:1:855157)
    at sN (72054.ccb12939fa7033320d60.js:1:838173)
    at 72054.ccb12939fa7033320d60.js:1:838039
    at sI (72054.ccb12939fa7033320d60.js:1:838047)
    at sx (72054.ccb12939fa7033320d60.js:1:835132)
    at r3 (72054.ccb12939fa7033320d60.js:1:783822)
    at sO (72054.ccb12939fa7033320d60.js:1:835636)
    at 72054.ccb12939fa7033320d60.js:1:863697
    at uu (72054.ccb12939fa7033320d60.js:1:863727)
    at t.render (72054.ccb12939fa7033320d60.js:1:867425)
    at MyReact.render (0BDFDB.plugin.js:2953:40)
    at MyReact.hookCall (0BDFDB.plugin.js:2968:23)
    at loadLibrary (0BDFDB.plugin.js:7973:60)
    at parseData (0BDFDB.plugin.js:1206:24)
    at parseCSS (0BDFDB.plugin.js:1167:122)
    at requestLibraryData (0BDFDB.plugin.js:1211:51)
    at eval (0BDFDB.plugin.js:1157:7)
    at eval (0BDFDB.plugin.js:222:56)`

**Comment by rauenzi** [comment]
That error is coming from Discord and/or DevilBro's library, nothing to do with mine
