### ISSUE TITLE
`0PluginLibrary.plugin.js` - error

### ISSUE THREAD

**Issue by Obegg** [rauenzi/BDPluginLibrary#224]
```js
TypeError: Cannot read properties of undefined (reading 'prototype')
    at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)
```

**Comment by Strana** [comment]
Just started getting this as well, same error

**Comment by parknich** [comment]
I'm getting the same thing

**Comment by Scorpions95** [comment]
As other users above, i have same issue as them
![Uploading Screenshot 2024-06-12 21.51.50.png…]()

**Comment by Scorpions95** [comment]
As other users above, i have same issue as them
https://prnt.sc/KLYw3RB3sfHG

**Comment by Rexxxyxyxy** [comment]
same here

**Comment by COokieMTS** [comment]
same here, idk even which plugins need it so i can make discord work fine without it keeps crashing and restarting discord on its own

**Comment by GabinoGaming123** [comment]
me too
![Screen Shot 2024-06-12 at 2 15 07 PM](https://github.com/rauenzi/BDPluginLibrary/assets/89490426/d093c069-a8fc-4f8c-bb1a-d336a2811259)

**Comment by GabinoGaming123** [comment]
![Screen Shot 2024-06-12 at 2 16 29 PM](https://github.com/rauenzi/BDPluginLibrary/assets/89490426/e9ec4e7d-09e6-444a-bd62-e60c1be6c4b8)

**Comment by nikitos881** [comment]
hm, not only my problem

**Comment by Unit-108** [comment]
I found 1XenoLib.plugin.js being within the plugins folder causes a crash. I found what seems to be a working temp fix on Lighty's Discord (MessageLoggerV2 and other plugin dev) for the ZeresPluginLibrary. I have all of my plugins now functioning with that but I cannot say if it is the right move. I hope this helps.

**Comment by nikitos881** [comment]
yeah, it seems like problem is also in MessageLoggerV2

**Comment by nikitos881** [comment]
it works without XenoLib

**Comment by nikitos881** [comment]
MessageLoggerV2 cant work witout XenoLib

**Comment by kurmirika** [comment]
Unit-108 do you know where I can find lighty's discord?

**Comment by nikitos881** [comment]
I cant understand. Last update was long time ago...why we have this problem only now

**Comment by Unit-108** [comment]
> Unit-108 do you know where I can find lighty's discord?

I don't know if it is appropriate for me to put all that here but, you can find what you are looking for here.
https://github.com/1Lighty/BetterDiscordPlugins

**Comment by illusionistsquirrel** [comment]
I don't even have this "XenoLib" in my plugins folder, so I'm not so sure it's that

**Comment by Unit-108** [comment]
I have a crude understanding of any of this but, a broken component of ZeresPluginLibrary (0PluginLibrary.plugin.js) is causing XenoLib (used for things like MessageLoggerV2) to crash Discord. Remove XenoLib to prevent crashing for now.

**Comment by nikitos881** [comment]
anyway....XenoLib was updated 3 mounth ago in repo...but this problem i got only now

**Comment by dafzor** [comment]
Even with only 0PluginLibrary.plugin.js I get the error, so seems the base plugin has an issue that's unrelated with XenoLib.

**Comment by Unit-108** [comment]
I found what 1Lighty changed to make it work. If you want to dig and change the code out on line 3843 within 0PluginLibrary.plugin.js, I must preface it is a bandaid and not a fix.
From: `const Swatch = ColorPickerComponents?.CustomColorButton.prototype.render.call({props: {}}).type;`
To: `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;`

Again I didn't figure this out or know what I am talking about, but this appears to be working for me with my plugins.

**Comment by marcus-universe** [comment]
Same Error ✌:
TypeError: Cannot read properties of undefined (reading 'prototype')
    at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at betterdiscord/renderer.js:5:4392

**Comment by nikitos881** [comment]
> I found what 1Lighty changed to make it work. If you want to dig and change the code out on line 3843 within 0PluginLibrary.plugin.js, I must preface it is a bandaid workaround and not a fix. From: `const Swatch = ColorPickerComponents?.CustomColorButton.prototype.render.call({props: {}}).type;` To: `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;`
> 
> Again I didn't figure this out or know what I am talking about, but this appears to be working for me with my plugins.

ah, thank you! And thank to 1Lighty! Work for me

**Comment by AuracleTech** [comment]
# INSTRUCTIONS HOW TO FIX

open in a text editor `C:\Users\YOUR USER\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js`
change line 3843 to `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;`
remove the second to last line containing `s;`

done

**Comment by nikitos881** [comment]
EditUsersv4.8.9 dont work now....just if someone need to know

**Comment by Ritticle** [comment]
> I found what 1Lighty changed to make it work. If you want to dig and change the code out on line 3843 within 0PluginLibrary.plugin.js, I must preface it is a bandaid workaround and not a fix. From: `const Swatch = ColorPickerComponents?.CustomColorButton.prototype.render.call({props: {}}).type;` To: `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;`
> 
> Again I didn't figure this out or know what I am talking about, but this appears to be working for me with my plugins.

Thank you!

**Comment by BallisticAri** [comment]
> # INSTRUCTIONS HOW TO FIX
> open in a text editor `C:\Users\YOUR USER\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js` change line 3843 to `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;` remove the second to last line containing `s;`
> 
> done



> # INSTRUCTIONS HOW TO FIX
> open in a text editor `C:\Users\YOUR USER\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js` change line 3843 to `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;` remove the second to last line containing `s;`
> 
> done



> # INSTRUCTIONS HOW TO FIX
> open in a text editor `C:\Users\YOUR USER\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js` change line 3843 to `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;` remove the second to last line containing `s;`
> 
> done

YOU ARE A LIFE SAVER

**Comment by misterpyrrhuloxia** [comment]
> EditUsersv4.8.9 dont work now....just if someone need to know

It worked perfectly for me just a few minutes ago.

**Comment by Scorpions95** [comment]
I don't see "s;" in my code
https://prnt.sc/eBPCFzCY93vC

**Comment by AuracleTech** [comment]
> I don't see "s;" in my code https://prnt.sc/eBPCFzCY93vC

Then probably just the first instruction would work, mine had `s;`, give it a try without removing the `s;` if it doesn't work reply with the error it gives you (copy paste), if not then you're good

**Comment by rampso** [comment]
> I found what 1Lighty changed to make it work. If you want to dig and change the code out on line 3843 within 0PluginLibrary.plugin.js, I must preface it is a bandaid workaround and not a fix. From: `const Swatch = ColorPickerComponents?.CustomColorButton.prototype.render.call({props: {}}).type;` To: `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;`
> 
> Again I didn't figure this out or know what I am talking about, but this appears to be working for me with my plugins.

Works

**Comment by skrilax91** [comment]
I suppose that a discord update just changed the `CustomColorPicker` webpack module, specially by replacing or deleting property `CustomColorButton`.

**Comment by rauenzi** [comment]
This has been fixed in the latest version.

**Comment by BubbliBlu** [comment]
> # INSTRUCTIONS HOW TO FIX
> open in a text editor `C:\Users\YOUR USER\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js` change line 3843 to `const Swatch = ColorPickerComponents?.CustomColorButton?.prototype?.render?.call({props: {}})?.type;` remove the second to last line of the whole file containing `s;`
> 
> done

Can verify that it works without needing to open the .js file.  Just had to click the pencil button on the plugin itself in BD to edit.

**Comment by skrilax91** [comment]
> This has been fixed in the latest version.

I was creating a merge ^^
