### ISSUE TITLE
Startup error. Can't loa

### ISSUE THREAD

**Issue by ZenMasta** [rauenzi/BDPluginLibrary#226]
![image](https://github.com/rauenzi/BDPluginLibrary/assets/823528/7d01aa42-b54e-414f-b4eb-6760fb5c7308)

TypeError: Cannot read properties of undefined (reading 'prototype')
    at ./src/ui/colorpicker.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3845:56)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/types/color.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5147:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4792:70)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6125:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1712:60)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3585:80)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:656:65)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at ./src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1567:67)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6168:41)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6215:65)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6322:3)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6325:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)

```md
## Discord Info
stable 301409 (2506b34) Host 1.0.9149 x64 (48589) Build Override: N/A Windows 10 64-bit (10.0.19045)

## BetterDiscord
stable 1.10.1

### Plugins (0 Enabled):
- BDFDB
- BetterFormattingRedux
- BetterRoleColors
- ChannelTabs
- DiscordFreeEmojis
- Double Click To Edit
- FavoriteMedia
- GameActivityToggle
- Hide Channels
- PluginRepo
- ReadAllNotificationsButton
- RoleMembers
- SplitLargeMessages
- ZeresPluginLibrary

### Themes (1 Enabled):
- ClearVision (Enabled)
```

**Comment by rauenzi** [comment]
Please download the latest version

**Comment by ZenMasta** [comment]
When I'm prompted to download through discord, it doesnt work. And the version I have is the same as here

2.0.19
Where else can I find it?
