### ISSUE TITLE
Plugin constructor() could not be fired.

### ISSUE THREAD

**Issue by Simperfy** [rauenzi/BDPluginLibrary#227]
Upon installation I'm receiving this error:
```
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4601:25)
    at aS (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:976238)
    at u (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1031454)
    at sF (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1014469)
    at https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1014335
    at sB (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1014343)
    at sO (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1011428)
    at r6 (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:960102)
    at sk (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1011932)
    at https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1039999
    at uu (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1040029)
    at t.render (https://discord.com/assets/67096.60fb03d0b62c1fe1124f.js:12:1043724)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4515:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6149:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by rauenzi** [comment]
Fixed in latest version.
