### ISSUE TITLE
Plugin constructor () could not be fired.

### ISSUE THREAD

**Issue by transdemonic** [rauenzi/BDPluginLibrary#236]
Received this error while opening bd using this plugin library:
```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:5579347
    at l (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:9528118)
    at c (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:9528505)
    at l (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:5579321)
    at p (https://discord.com/assets/76691fb613307173f03a.js:1:5958)
    at aA (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:990633)
    at l (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1045869)
    at ok (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1028864)
    at https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1028730
    at oG (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1028738)
    at oD (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1025823)
    at r5 (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:974497)
    at ob (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1026327)
    at https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1054414
    at ll (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1054444)
    at t.render (https://discord.com/assets/web.fcc22e0c2b6b7be1cf98.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235
```

This is my first time doing this, so I'm sorry if I'm doing it incorrectly.

**Comment by itmesarah** [comment]
Duplicate of #231

**Comment by transdemonic** [comment]
Oh, apologies, I didn't see that it was a closed issue. Thank you.
